


GET https://localhost:4000/auction

###

GET https://localhost:4000/auction/2398aa75-099a-4a7f-bcf2-2c380c2d3baa

###

GET https://localhost:4000/auction/art/e44f21af-a7c3-4c64-bf26-6c10edd4d0c3

###


POST https://localhost:4000/auction
content-type: application/json

{
  "art_uuid": "3e467f25-1a63-4a68-9f65-73617fff97fb",
  "start_time": "2021-03-25T16:05:00+09:00",
  "end_time":"2021-03-25T16:05:00+09:00",
  "hammer_price":"1000",
  "now_price":"0"
}

###

PUT https://localhost:4000/auction/2398aa75-099a-4a7f-bcf2-2c380c2d3baa
content-type: application/json

  # "art_uuid": "e44f21af-a7c3-4c64-bf26-6c10edd4d0c3",
{
  "end_time": "2021-03-18T19:54:36.000Z",
  "hammer_price": 100000,
  "now_price": 10000,
  "link": "https://exitgift.shop",
  "start_time": "2021-03-19T12:44:22.000Z"
}

###

DELETE https://localhost:4000/auction/2398aa75-099a-4a7f-bcf2-2c380c2d3baa
