###
POST https://localhost:4000/signup
content-type: application/json

{
  "user_password": "1234",
  "user_email": "crypto1@crypto1.com"
}

###
POST https://localhost:4000/signin
Content-Type: application/json

{
  "user_email": "guest@guest.com",
  "user_password": "guest"
}

###
GET https://localhost:4000/accessTokenRequest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXVpZCI6ImM3MjYzOTNlLTQ2ZDYtNGFkNS05NzY0LTBkYzhmZTBhMDU2OCIsInVzZXJfdXNlX2N1cnJlbmN5IjoiJCIsInVzZXJfdXNlX2xhbmd1YWdlIjoia29yIiwidXNlcl90eXBlIjoiZ3Vlc3QiLCJ1c2VyX2VtYWlsIjoiZ3Vlc3RAZ3Vlc3QuY29tIiwidXNlcl9uaWNrIjoiZ3Vlc3QiLCJ3YWxsZXRfbm93X2RlcG9zaXQiOjEwMDAwMDAwLCJ3YWxsZXRfbm93X2NvaW4iOjEwMCwiY3JlYXRlZEF0IjoiMjAyMS0wMy0xOFQwOToxNjoyOS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wMy0xOFQwOToxNjoyOS4wMDBaIiwiaWF0IjoxNjE2MjI2Njc0LCJleHAiOjE2MTYyMjY2ODl9.mNrKCeMRI4j8kbJ-EVYhS_zQpXGC1GxItOrFoHgvuEU

###
GET https://localhost:4000/refreshTokenRequest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiYzcyNjM5M2UtNDZkNi00YWQ1LTk3NjQtMGRjOGZlMGEwNTY4IiwidXNlcl91c2VfY3VycmVuY3kiOiIkIiwidXNlcl91c2VfbGFuZ3VhZ2UiOiJrb3IiLCJ1c2VyX3R5cGUiOiJndWVzdCIsInVzZXJfZW1haWwiOiJndWVzdEBndWVzdC5jb20iLCJ1c2VyX25pY2siOiJndWVzdCIsIndhbGxldF9ub3dfZGVwb3NpdCI6MTAwMDAwMDAsIndhbGxldF9ub3dfY29pbiI6MTAwLCJjcmVhdGVkQXQiOiIyMDIxLTAzLTE4VDA5OjE2OjI5LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTAzLTE4VDA5OjE2OjI5LjAwMFoiLCJpYXQiOjE2MTYzMjczNzQsImV4cCI6MTYxODkxOTM3NH0.03It66TipUUEtggbovilOR55qevXeZlY2pCRaG_WQz0

###
POST https://localhost:4000/signout
