###
POST https://localhost:4000/signup
content-type: application/json

{
  "user_password": "1234",
  "user_email": "crypto1@crypto1.com"
}

###
POST https://localhost:4000/signin
Content-Type: application/json

{
  "user_email": "1@1.com",
  "user_password": "1234"
}

###
GET https://localhost:4000/accessTokenRequest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMWRjM2Y4OGQtM2IwYi00MDg0LTk1NzAtYjk5NTIzMzE2NzkyIiwidXNlcl91c2VfY3VycmVuY3kiOiIkIiwidXNlcl91c2VfbGFuZ3VhZ2UiOiJrb3IiLCJ1c2VyX3R5cGUiOiJvYXV0aCIsInVzZXJfZW1haWwiOiJuYW5zOTEwNTIxQGdtYWlsLmNvbSIsInVzZXJfbmljayI6Im51bGwiLCJ3YWxsZXRfbm93X2RlcG9zaXQiOjAsIndhbGxldF9ub3dfY29pbiI6MCwiY3JlYXRlZEF0IjoiMjAyMS0wMy0yMFQxMzozNDo1NS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wMy0yMFQxMzozNDo1NS4wMDBaIiwiaWF0IjoxNjE2Mzg4MDQ5LCJleHAiOjE2MTYzODgwNjR9.jI1kjTxtO7dowjORootBhTI3C28ACov9ggScuAUIC9Y

###
GET https://localhost:4000/refreshTokenRequest

###
GET https://localhost:4000/signout

